/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rentalpc;

import java.awt.Color;
import java.awt.Cursor;
import javax.swing.JOptionPane;
import view.MenuDaftarPeminjam;
import view.MenuTransaksi;

/**
 *
 * @author ACER
 */
public class FUtama extends javax.swing.JFrame {

    /**
     * Creates new form FUtama
     */
    public FUtama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_navbar = new javax.swing.JPanel();
        btnTransaksi = new javax.swing.JLabel();
        btnDaftarPinjam = new javax.swing.JLabel();
        pn_dasar = new javax.swing.JPanel();
        pn_utama = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pn_navbar.setBackground(new java.awt.Color(204, 255, 204));

        btnTransaksi.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        btnTransaksi.setForeground(new java.awt.Color(51, 51, 51));
        btnTransaksi.setText("Transaksi");
        btnTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTransaksiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTransaksiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTransaksiMouseExited(evt);
            }
        });

        btnDaftarPinjam.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        btnDaftarPinjam.setForeground(new java.awt.Color(51, 51, 51));
        btnDaftarPinjam.setText("Daftar Peminjam");
        btnDaftarPinjam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDaftarPinjamMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDaftarPinjamMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDaftarPinjamMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_navbarLayout = new javax.swing.GroupLayout(pn_navbar);
        pn_navbar.setLayout(pn_navbarLayout);
        pn_navbarLayout.setHorizontalGroup(
            pn_navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_navbarLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnTransaksi)
                .addGap(43, 43, 43)
                .addComponent(btnDaftarPinjam)
                .addContainerGap(419, Short.MAX_VALUE))
        );
        pn_navbarLayout.setVerticalGroup(
            pn_navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_navbarLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(pn_navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTransaksi)
                    .addComponent(btnDaftarPinjam))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        getContentPane().add(pn_navbar, java.awt.BorderLayout.PAGE_START);

        pn_dasar.setBackground(new java.awt.Color(204, 255, 204));

        pn_utama.setPreferredSize(new java.awt.Dimension(808, 348));
        pn_utama.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout pn_dasarLayout = new javax.swing.GroupLayout(pn_dasar);
        pn_dasar.setLayout(pn_dasarLayout);
        pn_dasarLayout.setHorizontalGroup(
            pn_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_dasarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(pn_utama, javax.swing.GroupLayout.DEFAULT_SIZE, 809, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        pn_dasarLayout.setVerticalGroup(
            pn_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_dasarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(pn_utama, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        getContentPane().add(pn_dasar, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTransaksiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTransaksiMouseEntered
        btnTransaksi.setForeground(Color.PINK);
        btnTransaksi.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnTransaksiMouseEntered

    private void btnTransaksiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTransaksiMouseExited
        btnTransaksi.setForeground(new Color(204,204,204));
        btnTransaksi.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));      
    }//GEN-LAST:event_btnTransaksiMouseExited

    private void btnDaftarPinjamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDaftarPinjamMouseEntered
        btnDaftarPinjam.setForeground(Color.PINK);
        btnDaftarPinjam.setCursor(new Cursor(Cursor.HAND_CURSOR));      
    }//GEN-LAST:event_btnDaftarPinjamMouseEntered

    private void btnDaftarPinjamMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDaftarPinjamMouseExited
        btnDaftarPinjam.setForeground(new Color(204,204,204));
        btnDaftarPinjam.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));    
    }//GEN-LAST:event_btnDaftarPinjamMouseExited

    private void btnTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTransaksiMouseClicked
        btnTransaksi.setForeground(new Color(204,204,0));
       
       //btn transaksi saat di klik
       pn_utama.removeAll();
       pn_utama.add(new MenuTransaksi());
       pn_utama.repaint();
       pn_utama.revalidate();
    }//GEN-LAST:event_btnTransaksiMouseClicked

    private void btnDaftarPinjamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDaftarPinjamMouseClicked
       btnDaftarPinjam.setForeground(new Color(204,204,0));
       
       //btn daftar saat di klik
       pn_utama.removeAll();
       pn_utama.add(new MenuDaftarPeminjam());
       pn_utama.repaint();
       pn_utama.revalidate();
    }//GEN-LAST:event_btnDaftarPinjamMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnDaftarPinjam;
    private javax.swing.JLabel btnTransaksi;
    private javax.swing.JPanel pn_dasar;
    private javax.swing.JPanel pn_navbar;
    private javax.swing.JPanel pn_utama;
    // End of variables declaration//GEN-END:variables
}
